name: LeetCode Typescript CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  unittest:
    needs: lint
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: install dependencies
        run: npm ci

      - name: unittest
        run: |
          npm test
          cp coverage/cobertura-coverage.xml coverage.xml

      - name: coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"
